// Command gen-site builds a landing page from a real report.
//
// It takes the output directory of an actual `entire impeach --out` run,
// scrubs machine-specific paths out of it, commits that as the sample report,
// copies the report's own stylesheet, and lifts the lead-impeachment block out
// of the sample verbatim.
//
// Lifting rather than rewriting is the point. The page's hero and the report's
// hero are the same bytes, so the two surfaces cannot drift into disagreeing
// about what the tool found. A test asserts that.
//
// # It will not overwrite a hand-written page
//
// The shipped site at impeach/site is no longer generated. Its index.html,
// style.css, site.js and fonts were written by hand, and its hero block is
// carried there deliberately, byte for byte, from the committed sample.
// Running this command against that directory used to replace all of it with
// the older generated version, and every test stayed green while it happened,
// because the generated page satisfies the same assertions: the hero is still
// lifted verbatim, there are still no machine paths, and there is still
// nothing loaded from another host. The drift gate was built to catch a
// hand-edited page and cannot see a regenerated one.
//
// So generated output now carries a marker, and this command refuses to write
// over an existing index.html or style.css that does not have it. The refusal
// is the whole run, not the one file: refreshing sample/ on its own would
// leave the hand-written hero pointing at evidence that had moved, which
// breaks the byte-identity guarantee just as thoroughly and less visibly.
//
// Usage, from the impeach module root:
//
//	go run ./internal/report/gen-site --from <dir> --repo <repo-root> --out /tmp/site
package main

import (
	"flag"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	from := flag.String("from", "", "directory holding impeach.json and impeach.html from a real run")
	repo := flag.String("repo", "", "repository root, replaced with <repo> in the committed sample")
	out := flag.String("out", "site", "directory to write the site into")
	force := flag.Bool("overwrite-hand-written", false, "replace an existing hand-written index.html or style.css instead of refusing")
	flag.Parse()

	if *from == "" {
		fail("--from is required: point it at the --out directory of a real impeach run")
	}
	if err := run(*from, *repo, *out, *force); err != nil {
		fail("%v", err)
	}
}

// The marker every generated file carries. Its absence in an existing file is
// what identifies that file as hand-written.
//
// In the page it rides on a <meta name="generator"> tag rather than in an HTML
// comment, because html/template strips comments out of a template as it
// parses it. The comment version compiled, rendered and vanished, leaving the
// command unable to recognise its own output, which is a marker that fails in
// the unsafe direction. In the stylesheet, which is copied rather than
// rendered, a CSS comment survives.
const (
	genMarker    = "generated by gen-site; do not hand edit"
	genMarkerCSS = "/* " + genMarker + " */"
)

// refuseHandWritten reports the outputs that already exist without the
// generated marker.
//
// It runs before anything is written, so a refusal leaves the directory
// exactly as it was. Only index.html and style.css are checked: sample/ holds
// the report artifact this command exists to refresh, and overwriting that is
// the intended act rather than the accident.
func refuseHandWritten(out string) error {
	var handWritten []string
	for _, name := range []string{"index.html", "style.css"} {
		path := filepath.Join(out, name)
		body, err := os.ReadFile(path)
		if err != nil {
			// Absent is the normal case and is not an error. Anything else is
			// reported rather than assumed to be absence.
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("check %s before overwriting it: %w", path, err)
		}
		if !strings.Contains(string(body), genMarker) {
			handWritten = append(handWritten, path)
		}
	}
	if len(handWritten) == 0 {
		return nil
	}
	return fmt.Errorf(`refusing to overwrite hand-written %s

The site under %s was written by hand and is not generated. Its hero block is
carried there byte for byte from site/sample/impeach.html, so replacing either
the page or its stylesheet with generated output silently reverts the site,
and the tests cannot see it happen.

Write somewhere else and copy what you want by hand:

    go run ./internal/report/gen-site --from <dir> --repo <repo-root> --out /tmp/site

If you have read impeach/site/README.md and mean to replace the page, pass
--overwrite-hand-written.`, strings.Join(handWritten, " and "), out)
}

func run(from, repo, out string, force bool) error {
	rawJSON, err := os.ReadFile(filepath.Join(from, "impeach.json"))
	if err != nil {
		return fmt.Errorf("read sample json: %w", err)
	}
	rawHTML, err := os.ReadFile(filepath.Join(from, "impeach.html"))
	if err != nil {
		return fmt.Errorf("read sample html: %w", err)
	}

	scrub := pathScrubber(repo)
	sampleJSON := scrub(string(rawJSON))
	sampleHTML := scrub(string(rawHTML))

	// The report's own stylesheet, copied rather than reimplemented, so the
	// two surfaces share one set of tokens by construction.
	css, err := os.ReadFile(filepath.Join("internal", "report", "report.css"))
	if err != nil {
		return fmt.Errorf("read report css: %w", err)
	}

	hero, err := extractSection(sampleHTML, "lead")
	if err != nil {
		return err
	}

	if !force {
		if err := refuseHandWritten(out); err != nil {
			return err
		}
	}

	if err := os.MkdirAll(filepath.Join(out, "sample"), 0o755); err != nil {
		return err
	}
	writes := map[string]string{
		filepath.Join(out, "sample", "impeach.json"): sampleJSON,
		filepath.Join(out, "sample", "impeach.html"): sampleHTML,
		filepath.Join(out, "style.css"):              genMarkerCSS + "\n" + string(css),
	}
	for path, body := range writes {
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	page, err := renderIndex(hero)
	if err != nil {
		return err
	}
	indexPath := filepath.Join(out, "index.html")
	if err := os.WriteFile(indexPath, page, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", indexPath, err)
	}

	fmt.Printf("wrote %s, %s/style.css and %s/sample/{impeach.json,impeach.html}\n", indexPath, out, out)
	return nil
}

// extractSection lifts one <section id="..."> ... </section> block verbatim.
//
// Verbatim matters: the hero on the landing page has to be the same bytes as
// the hero in the report, or the page becomes a second, drifting account of
// the same audit.
func extractSection(page, id string) (string, error) {
	open := fmt.Sprintf(`<section id=%q>`, id)
	start := strings.Index(page, open)
	if start < 0 {
		return "", fmt.Errorf("no <section id=%q> in the sample report; the template changed and gen-site needs updating", id)
	}
	rest := page[start:]
	end := strings.Index(rest, "</section>")
	if end < 0 {
		return "", fmt.Errorf("section %q is not terminated in the sample report", id)
	}
	return rest[:end+len("</section>")], nil
}

// pathScrubber rewrites machine-specific paths out of the committed sample.
//
// A locally generated report shows real paths on purpose, so a reader can
// copy a reproduce command and run it. A committed one must not: it would
// publish the author's home directory to anyone who opens the page.
func pathScrubber(repo string) func(string) string {
	// Only absolute paths, and only ones long enough to be unambiguous.
	//
	// An earlier version also replaced the raw --repo argument as given.
	// Passing --repo .. then rewrote every literal ".." in the report, which
	// turned pytest's "...." progress line into "<repo><repo>" and corrupted
	// real evidence. A scrubber that damages the output it is protecting is
	// worse than no scrubber, so a replacement now has to be an absolute
	// path of at least this many characters to be applied at all.
	const minLen = 8

	var pairs [][2]string
	add := func(from, to string) {
		if len(from) >= minLen && filepath.IsAbs(from) {
			pairs = append(pairs, [2]string{from, to})
		}
	}
	if repo != "" {
		if abs, err := filepath.Abs(repo); err == nil {
			add(abs, "<repo>")
		}
	}
	if home, err := os.UserHomeDir(); err == nil {
		add(home, "<home>")
	}
	// Longest first, so a home directory nested inside a repository path, or
	// the reverse, does not leave a partly rewritten string behind.
	sort.Slice(pairs, func(i, j int) bool { return len(pairs[i][0]) > len(pairs[j][0]) })

	// The user name is replaced only as a whole path segment, never as a bare
	// substring, for the same reason.
	user := os.Getenv("USER")
	return func(s string) string {
		for _, p := range pairs {
			s = strings.ReplaceAll(s, p[0], p[1])
		}
		if len(user) > 2 {
			s = strings.ReplaceAll(s, "/"+user+"/", "/<user>/")
		}
		return s
	}
}

func renderIndex(hero string) ([]byte, error) {
	tmpl, err := template.New("index").Parse(indexTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse index template: %w", err)
	}
	var b strings.Builder
	// The hero is trusted because it came from our own renderer, which
	// already escaped every value it placed. Re-escaping would render the
	// markup as text.
	if err := tmpl.Execute(&b, map[string]any{"Hero": template.HTML(hero)}); err != nil {
		return nil, fmt.Errorf("render index: %w", err)
	}
	return []byte(b.String()), nil
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-site: "+format+"\n", args...)
	os.Exit(1)
}
